-- Consolidated baseline schema (migration v1).
--
-- This file is the single source of truth for a fresh install: it
-- reflects the full schema after the original schema plus every
-- incremental migration (remote storage columns, schema_slug, view
-- config, trigram FTS, etc.) collapsed into one baseline. The prior
-- 1..13 migration chain was squashed here; `_sqlx_migrations` is
-- reconciled to a single v1 row so existing databases keep their data.
--
-- To evolve the schema, add a new numbered migration in
-- `mod.rs::get_migrations()` — do NOT edit this file (it would change
-- migration v1's checksum and break every existing database).

-- Categories table
CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    icon TEXT,
    is_default BOOLEAN DEFAULT 0,
    folder_name TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    schema_slug TEXT NOT NULL DEFAULT 'novel',
    view_config TEXT
);

-- Files table
CREATE TABLE IF NOT EXISTS files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    path TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    file_status TEXT DEFAULT 'available' CHECK (file_status IN ('available', 'missing', 'moved')),
    in_storage BOOLEAN DEFAULT 0,
    original_path TEXT,
    progress TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    storage_kind TEXT NOT NULL DEFAULT 'local',
    remote_provider TEXT,
    remote_fs_id TEXT,
    remote_size INTEGER,
    remote_md5 TEXT,
    local_cache_path TEXT
);

-- App settings table
CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Default storage path setting
INSERT INTO app_settings (key, value) VALUES ('storage_path', '');

-- Tags table
CREATE TABLE IF NOT EXISTS tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    color TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- File-Tag junction table
CREATE TABLE IF NOT EXISTS file_tags (
    file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (file_id, tag_id)
);

-- Metadata table
CREATE TABLE IF NOT EXISTS metadata (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    data_type TEXT DEFAULT 'text' CHECK (data_type IN ('text', 'number', 'date', 'boolean')),
    UNIQUE(file_id, key)
);

-- Authors table
CREATE TABLE IF NOT EXISTS authors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- File-Author junction table
CREATE TABLE IF NOT EXISTS file_authors (
    file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    author_id INTEGER NOT NULL REFERENCES authors(id) ON DELETE CASCADE,
    PRIMARY KEY (file_id, author_id)
);

-- Covers table (stores cover images as BLOB)
CREATE TABLE IF NOT EXISTS covers (
    file_id INTEGER PRIMARY KEY REFERENCES files(id) ON DELETE CASCADE,
    data BLOB NOT NULL,
    mime_type TEXT DEFAULT 'image/png',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Prompts table (LLM prompt management)
CREATE TABLE IF NOT EXISTS prompts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT,
    is_default INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    mime_group TEXT NOT NULL DEFAULT 'text',
    step TEXT NOT NULL DEFAULT 'filename',
    schema_slug TEXT
);

-- Default prompts. `content` uses unistr() so embedded newlines stay
-- legible; bundled SQLite (>= 3.42) supports it. schema_slug + step are
-- the routing keys read by the prompt resolver.
INSERT INTO prompts (name, content, category, is_default, mime_group, step, schema_slug) VALUES
('Filename Extraction', ('Extract metadata from this filename only. Rules:
- display_name: the clean title (remove site prefixes like [sxsy.org], brackets, brace, file extension or content inside title marks)
- progress: combine chapter range + status, e.g. "1-45章", “完结”, if still unknown, return “完结"
- authors: if filename has "作者：xxx" or “ display_name progress xxx” pattern, extract the author, if still unknown, return “佚名"

example:
淫仙路 1-244 世间 =>  display_name 淫仙路 progress 1-244章 author 世间
一对百合被体育生胁迫调教，在失禁与潮吹中沦为专属母狗作者Wilde => display_name 一对百合被体育生胁迫调教，在失禁与潮吹中沦为专属母狗 progress 完结 author Wilde
三千劫后，继承绝色仙子们的调教契约-1-18-闲读 => display_name 三千劫后，继承绝色仙子们的调教契约 progress 1-18章 author 闲读
我的道侣都太诡异了 1-126章 逆时针的圈 => display_name 我的道侣都太诡异了 progress 1-126章 author 逆时针的圈'), 'filename', 1, 'text', 'filename', 'novel'),
('Content Analysis', ('- category: return ONLY the category name. If a category is shown as "name (description)", the parenthesized text is just a hint — return "name" without the parentheses or description. By default, value is novel.
- tags: at most 6 total; prefer existing tags; only propose new ones when you''re confident they clearly apply — be confident, precise, not eager
- Use null for unknown fields'), 'content', 1, 'text', 'content', 'novel'),
('Comic Filename Extraction', ('Extract metadata from this comic archive filename only. Rules:
- display_name: clean comic title, can include volume/chapter markers like 第01-10话/Vol.5/Ch.42) (strip site prefixes like [sxsy.org], scanlator brackets like [天蝎座汉化], the file extension. DO NOT translate.
- authors: extract the original author/artist if present (patterns: ’[xxx]’, or pulled from the title itself when obvious), Treat scanlator/translator credits as NOT authors
- Use null for unknown fields

Example:
[非凡 (伊丹)] 催眠NTRカノジョ [不可视汉化] [DL版] => display_name: 催眠NTRカノジョ author: 非凡 (伊丹)
[Amerins補漢] [めめゆ] ひとりじめラブドール [DL版] => display_name: ひとりじめラブドール author: めめゆ
[ホイホイこーろ、跡美くぼむ] 元・非モテ童貞は見返したい！～ビッチ五姉妹攻略ゲーム～ 1話 [结城铃兰个人汉化] [DL版] => display_name: 元・非モテ童貞は見返したい！～ビッチ五姉妹攻略ゲーム～ 1話 author: ホイホイこーろ、跡美くぼむ

Some Rules:
for author extract, braces are considered part author, not complete. such as [非凡 (伊丹)] author is 非凡 (伊丹), not 伊丹. [TYPE.90] author is TYPE.90. [ビフィダス] author is ビフィダス'), 'archive_filename', 1, 'archive', 'filename', 'comic'),
('Comic Cover Detection', ('You are picking the cover image of a comic archive given the list of image filenames inside it. Rules:
- Return up to 5 filenames from the input list, ordered best-first.
- The first file in the input (often named 000.jpg, 001.png, cover.jpg, cover01.jpg) is usually the cover — rank it first when plausible.
- Filenames containing ''cover'', ''front'', ''title'', or ''扉'' (Chinese for ''title page'') are strong cover signals.
- Return the filenames verbatim — do not invent entries.
- If nothing looks like a cover, return an empty list.'), 'comic_cover_pick', 1, 'archive', 'cover_pick', 'comic'),
('Image Folder Filename Extraction', ('Extract metadata from this image-folder name only. DO NOT extract authors here. Rules:
- display_name: clean comic title (strip site prefixes like [sxsy.org], scanlator brackets like [天蝎座汉化] / [镜面光折射汉化], date prefixes like [2022.12]). DO NOT translate.
- authors: always return an empty list. Authors are NOT extracted from folder names in this prompt.
- Use null for unknown fields (other than authors, which is always empty).'), 'image_folder_filename', 1, 'image_folder', 'filename_folder', 'comic');

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_files_category ON files(category_id);
CREATE INDEX IF NOT EXISTS idx_files_status ON files(file_status);
CREATE INDEX IF NOT EXISTS idx_files_name ON files(display_name);
CREATE INDEX IF NOT EXISTS idx_files_storage_kind ON files(storage_kind);
CREATE INDEX IF NOT EXISTS idx_file_tags_tag ON file_tags(tag_id);
CREATE INDEX IF NOT EXISTS idx_metadata_file ON metadata(file_id);
CREATE INDEX IF NOT EXISTS idx_metadata_key ON metadata(key);
CREATE INDEX IF NOT EXISTS idx_file_authors_author ON file_authors(author_id);
CREATE INDEX IF NOT EXISTS idx_categories_schema_slug ON categories(schema_slug);
CREATE INDEX IF NOT EXISTS idx_prompts_mime_step ON prompts(mime_group, step);
CREATE INDEX IF NOT EXISTS idx_prompts_schema_step ON prompts(schema_slug, step);

-- Full-text search virtual table (trigram tokenizer: substring + CJK).
CREATE VIRTUAL TABLE IF NOT EXISTS files_fts USING fts5(
    display_name,
    path,
    content='files',
    content_rowid='id',
    tokenize='trigram'
);

-- Triggers to keep FTS in sync
CREATE TRIGGER IF NOT EXISTS files_ai AFTER INSERT ON files BEGIN
    INSERT INTO files_fts(rowid, display_name, path) VALUES (NEW.id, NEW.display_name, NEW.path);
END;

CREATE TRIGGER IF NOT EXISTS files_ad AFTER DELETE ON files BEGIN
    INSERT INTO files_fts(files_fts, rowid, display_name, path) VALUES ('delete', OLD.id, OLD.display_name, OLD.path);
END;

CREATE TRIGGER IF NOT EXISTS files_au AFTER UPDATE ON files BEGIN
    INSERT INTO files_fts(files_fts, rowid, display_name, path) VALUES ('delete', OLD.id, OLD.display_name, OLD.path);
    INSERT INTO files_fts(rowid, display_name, path) VALUES (NEW.id, NEW.display_name, NEW.path);
END;
