/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsTagIdRouteImport } from './routes/tags_.$tagId'
import { Route as AuthorsAuthorIdRouteImport } from './routes/authors_.$authorId'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagIdRoute = TagsTagIdRouteImport.update({
  id: '/tags_/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: '/authors_/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/categories': typeof CategoriesRoute
  '/prompts': typeof PromptsRoute
  '/tags': typeof TagsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/categories': typeof CategoriesRoute
  '/prompts': typeof PromptsRoute
  '/tags': typeof TagsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/categories': typeof CategoriesRoute
  '/prompts': typeof PromptsRoute
  '/tags': typeof TagsRoute
  '/authors_/$authorId': typeof AuthorsAuthorIdRoute
  '/tags_/$tagId': typeof TagsTagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authors'
    | '/categories'
    | '/prompts'
    | '/tags'
    | '/authors/$authorId'
    | '/tags/$tagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authors'
    | '/categories'
    | '/prompts'
    | '/tags'
    | '/authors/$authorId'
    | '/tags/$tagId'
  id:
    | '__root__'
    | '/'
    | '/authors'
    | '/categories'
    | '/prompts'
    | '/tags'
    | '/authors_/$authorId'
    | '/tags_/$tagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsRoute: typeof AuthorsRoute
  CategoriesRoute: typeof CategoriesRoute
  PromptsRoute: typeof PromptsRoute
  TagsRoute: typeof TagsRoute
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  TagsTagIdRoute: typeof TagsTagIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags_/$tagId': {
      id: '/tags_/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof TagsTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors_/$authorId': {
      id: '/authors_/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsRoute: AuthorsRoute,
  CategoriesRoute: CategoriesRoute,
  PromptsRoute: PromptsRoute,
  TagsRoute: TagsRoute,
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  TagsTagIdRoute: TagsTagIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
