/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as CleanupRouteImport } from './routes/cleanup'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as IndexRouteImport } from './routes/index'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanupRoute = CleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/categories': typeof CategoriesRoute
  '/cleanup': typeof CleanupRoute
  '/prompts': typeof PromptsRoute
  '/tags': typeof TagsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/categories': typeof CategoriesRoute
  '/cleanup': typeof CleanupRoute
  '/prompts': typeof PromptsRoute
  '/tags': typeof TagsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/categories': typeof CategoriesRoute
  '/cleanup': typeof CleanupRoute
  '/prompts': typeof PromptsRoute
  '/tags': typeof TagsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authors'
    | '/categories'
    | '/cleanup'
    | '/prompts'
    | '/tags'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authors' | '/categories' | '/cleanup' | '/prompts' | '/tags'
  id:
    | '__root__'
    | '/'
    | '/authors'
    | '/categories'
    | '/cleanup'
    | '/prompts'
    | '/tags'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsRoute: typeof AuthorsRoute
  CategoriesRoute: typeof CategoriesRoute
  CleanupRoute: typeof CleanupRoute
  PromptsRoute: typeof PromptsRoute
  TagsRoute: typeof TagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanup': {
      id: '/cleanup'
      path: '/cleanup'
      fullPath: '/cleanup'
      preLoaderRoute: typeof CleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsRoute: AuthorsRoute,
  CategoriesRoute: CategoriesRoute,
  CleanupRoute: CleanupRoute,
  PromptsRoute: PromptsRoute,
  TagsRoute: TagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
